version: '3.9'


services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    entrypoint: sh -c "alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - 9999:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d restaurant"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
  rabbitmq:
    container_name: "rabitmq"
    image: rabbitmq:alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  celery-worker:
    build: .
    volumes:
      - .:/app/celery
    command: celery -A app.tasks.celery_worker:celery_app worker --loglevel=info
    depends_on:
      - app
      - rabbitmq
  celery-beat:
    build: .
    volumes:
      - .:/app/celery
    command: celery -A app.tasks.celery_worker:celery_app beat
    depends_on:
      rabbitmq:
          condition: service_healthy
      app:
        condition: service_started
